name: Mirror Repository

on:
  push:
    branches:
      - dev

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: EpitechPromo2026/B-CPP-500-TLS-5-1-rtype-younes1.bahri
          ref: main
          token: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Config user
        run: |
          git config --global user.email "abdelkader.mazouz@epitech.eu"
          git config --global user.name "Amaz31"
          cd B-CPP-500-TLS-5-1-rtype-younes1.bahri/Engine

      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Push to Target Repository
        run: |
          rm -rf .git
          cd ..
          git add .
          git commit -m "add Uniti repo"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.SSH_PRIVATE_KEY }}